In [1]:
from tensorflow import keras

2022-11-07 15:51:04.314052: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-07 15:51:04.509829: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-07 15:51:04.591720: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-07 15:51:05.539973: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; 

In [2]:
from skimage import io

nlcd_test = io.imread("NAIP_NLCD_train_2013/NLCD/img/496_1.png")
nlcd_test

array([[21, 21, 21, ..., 41, 41, 41],
       [21, 21, 21, ..., 41, 41, 41],
       [21, 21, 21, ..., 41, 41, 41],
       ...,
       [41, 41, 41, ..., 41, 41, 41],
       [41, 41, 41, ..., 41, 41, 41],
       [41, 41, 41, ..., 41, 41, 41]], dtype=uint8)

In [3]:
import utils
import numpy as np

In [4]:
def nlcd_preprocess(img):
    # map from orignal ints to ints within 0 to 5
    remapper = lambda x: utils.nlcd_2_int_mapping[x]
    return np.vectorize(remapper)(img)

In [5]:
nlcd_test = nlcd_preprocess(nlcd_test)
nlcd_test

array([[2, 2, 2, ..., 1, 1, 1],
       [2, 2, 2, ..., 1, 1, 1],
       [2, 2, 2, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [6]:
layer = keras.layers.CategoryEncoding(num_tokens=5, output_mode="one_hot")

In [7]:
a = keras.utils.to_categorical(nlcd_test, num_classes=5)
a.shape

(256, 256, 5)

In [8]:
nlcd_test[0][0]

2

In [9]:
a[0][0]

array([0., 0., 1., 0., 0.], dtype=float32)

In [10]:
a = np.array([
    [11, 22, 23],
    [24, 31, 41],
    [42, 43, 52],
    [71, 81, 82]
])

In [34]:
b = []

In [38]:
c = np.vectorize(lambda x: softmap[x], signature='()->(n)')(a)
c

array([[[0.98, 0.2 , 0.  , 0.  ],
        [0.  , 0.39, 0.49, 0.12],
        [0.01, 0.13, 0.22, 0.64]],

       [[0.  , 0.03, 0.07, 0.9 ],
        [0.05, 0.13, 0.43, 0.4 ],
        [0.  , 0.93, 0.05, 0.  ]],

       [[0.  , 0.95, 0.04, 0.  ],
        [0.  , 0.92, 0.07, 0.  ],
        [0.  , 0.58, 0.38, 0.04]],

       [[0.01, 0.23, 0.54, 0.22],
        [0.  , 0.12, 0.83, 0.03],
        [0.  , 0.05, 0.92, 0.01]]])

In [35]:
b.append(c)
b = np.array(b)
b.shape

(1, 4, 3, 4)

In [21]:
test = np.array([1, 2, 3])

mapp = {1: np.array([2, 3]), 2: np.array([1, 3]), 3: np.array([1, 2])}

np.vectorize(lambda x: mapp[x], signature='()->(n)')(test)

array([[2, 3],
       [1, 3],
       [1, 2]])

In [27]:
softmap = {
    11: np.array([0.98, 0.2, 0.0, 0.0]),
    22: np.array([0.0, 0.39, 0.49, 0.12]),
    23: np.array([0.01, 0.13, 0.22, 0.64]),
    24: np.array([0, 0.03, 0.07, 0.9]),
    31: np.array([0.05, 0.13, 0.43, 0.4]),
    41: np.array([0, 0.93, 0.05, 0]),
    42: np.array([0, 0.95, 0.04, 0]),
    43: np.array([0, 0.92, 0.07, 0]),
    52: np.array([0, 0.58, 0.38, 0.04]),
    71: np.array([0.01, 0.23, 0.54, 0.22]),
    81: np.array([0, 0.12, 0.83, 0.03]),
    82: np.array([0, 0.05, 0.92, 0.01]),
}