In [1]:
from tensorflow import keras

2022-11-06 15:32:20.868626: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-06 15:32:21.078882: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-06 15:32:21.129168: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-06 15:32:22.105832: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; 

In [2]:
from skimage import io

nlcd_test = io.imread("NAIP_NLCD_train_2013/NLCD/img/496_1.png")
nlcd_test

array([[21, 21, 21, ..., 41, 41, 41],
       [21, 21, 21, ..., 41, 41, 41],
       [21, 21, 21, ..., 41, 41, 41],
       ...,
       [41, 41, 41, ..., 41, 41, 41],
       [41, 41, 41, ..., 41, 41, 41],
       [41, 41, 41, ..., 41, 41, 41]], dtype=uint8)

In [11]:
import utils
import numpy as np

In [8]:
def nlcd_preprocess(img):
    # map from orignal ints to ints within 0 to 5
    remapper = lambda x: utils.nlcd_2_int_mapping[x]
    return np.vectorize(remapper)(img)

In [12]:
nlcd_test = nlcd_preprocess(nlcd_test)
nlcd_test

array([[2, 2, 2, ..., 1, 1, 1],
       [2, 2, 2, ..., 1, 1, 1],
       [2, 2, 2, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [4]:
layer = keras.layers.CategoryEncoding(num_tokens=5, output_mode="one_hot")

In [15]:
a = keras.utils.to_categorical(nlcd_test, num_classes=5)
a.shape

(256, 256, 5)

In [17]:
nlcd_test[0][0]

2

In [18]:
a[0][0]

array([0., 0., 1., 0., 0.], dtype=float32)